import { DataTypes } from 'sequelize';

export async function up(queryInterface) {
  // 1. travel_search_sessions
  await queryInterface.createTable('travel_search_sessions', {
    id: { type: DataTypes.STRING, primaryKey: true },
    userId: { type: DataTypes.STRING, allowNull: true },
    serviceType: { type: DataTypes.ENUM('FLIGHT', 'HOTEL', 'BUS', 'CAR'), allowNull: false },
    provider: { type: DataTypes.STRING, allowNull: false, defaultValue: 'SRDV' },
    searchParams: { type: DataTypes.JSON, allowNull: false },
    requestSnapshot: { type: DataTypes.JSON, allowNull: true },
    resultSnapshot: { type: DataTypes.JSON, allowNull: true },
    traceId: { type: DataTypes.STRING, allowNull: true },
    resultCount: { type: DataTypes.INTEGER, defaultValue: 0 },
    status: { type: DataTypes.STRING, defaultValue: 'COMPLETED' },
    expiresAt: { type: DataTypes.DATE, allowNull: true },
    createdAt: { type: DataTypes.DATE, allowNull: false },
    updatedAt: { type: DataTypes.DATE, allowNull: false }
  });

  // 2. package_service_items
  await queryInterface.createTable('package_service_items', {
    id: { type: DataTypes.STRING, primaryKey: true },
    packageId: { type: DataTypes.INTEGER, allowNull: true },
    itineraryDayId: { type: DataTypes.STRING, allowNull: false },
    serviceType: { type: DataTypes.ENUM('FLIGHT', 'HOTEL', 'BUS', 'CAR'), allowNull: false },
    status: { type: DataTypes.STRING, allowNull: false, defaultValue: 'SELECTED' },
    provider: { type: DataTypes.STRING, allowNull: false, defaultValue: 'SRDV' },
    traceId: { type: DataTypes.STRING, allowNull: true },
    srdvType: { type: DataTypes.STRING, allowNull: true },
    srdvIndex: { type: DataTypes.STRING, allowNull: true },
    resultIndex: { type: DataTypes.STRING, allowNull: true },
    hotelCode: { type: DataTypes.STRING, allowNull: true },
    providerReferences: { type: DataTypes.JSON, allowNull: true },
    searchSnapshot: { type: DataTypes.JSON, allowNull: true },
    selectedResultSnapshot: { type: DataTypes.JSON, allowNull: false },
    detailSnapshot: { type: DataTypes.JSON, allowNull: true },
    fareRuleSnapshot: { type: DataTypes.JSON, allowNull: true },
    seatMapSnapshot: { type: DataTypes.JSON, allowNull: true },
    ssrSnapshot: { type: DataTypes.JSON, allowNull: true },
    roomSnapshot: { type: DataTypes.JSON, allowNull: true },
    boardingSnapshot: { type: DataTypes.JSON, allowNull: true },
    selectedOptions: { type: DataTypes.JSON, allowNull: true },
    pricingSnapshot: { type: DataTypes.JSON, allowNull: false },
    createdAt: { type: DataTypes.DATE, allowNull: false },
    updatedAt: { type: DataTypes.DATE, allowNull: false }
  });

  // 3. service_api_logs
  await queryInterface.createTable('service_api_logs', {
    id: { type: DataTypes.STRING, primaryKey: true },
    userId: { type: DataTypes.STRING, allowNull: true },
    packageId: { type: DataTypes.INTEGER, allowNull: true },
    serviceItemId: { type: DataTypes.STRING, allowNull: true },
    bookingId: { type: DataTypes.STRING, allowNull: true },
    serviceType: { type: DataTypes.STRING, allowNull: false },
    action: { type: DataTypes.STRING, allowNull: false },
    provider: { type: DataTypes.STRING, allowNull: false, defaultValue: 'SRDV' },
    endpoint: { type: DataTypes.STRING, allowNull: false },
    httpMethod: { type: DataTypes.STRING, allowNull: false, defaultValue: 'POST' },
    requestJson: { type: DataTypes.JSON, allowNull: true },
    responseJson: { type: DataTypes.JSON, allowNull: true },
    httpStatus: { type: DataTypes.INTEGER, allowNull: true },
    providerErrorCode: { type: DataTypes.STRING, allowNull: true },
    providerErrorMessage: { type: DataTypes.TEXT, allowNull: true },
    traceId: { type: DataTypes.STRING, allowNull: true },
    latency: { type: DataTypes.INTEGER, defaultValue: 0 },
    status: { type: DataTypes.STRING, defaultValue: 'SUCCESS' },
    createdAt: { type: DataTypes.DATE, allowNull: false },
    updatedAt: { type: DataTypes.DATE, allowNull: false }
  });

  // 4. payments
  await queryInterface.createTable('payments', {
    id: { type: DataTypes.STRING, primaryKey: true },
    userId: { type: DataTypes.STRING, allowNull: true },
    packageId: { type: DataTypes.INTEGER, allowNull: true },
    serviceItemId: { type: DataTypes.STRING, allowNull: true },
    bookingId: { type: DataTypes.STRING, allowNull: true },
    serviceType: { type: DataTypes.ENUM('FLIGHT', 'HOTEL', 'BUS', 'CAR', 'PACKAGE'), allowNull: false },
    gateway: { type: DataTypes.STRING, allowNull: false, defaultValue: 'RAZORPAY_TEST' },
    gatewayOrderId: { type: DataTypes.STRING, allowNull: false, unique: true },
    gatewayPaymentId: { type: DataTypes.STRING, allowNull: true },
    gatewaySignature: { type: DataTypes.STRING, allowNull: true },
    amount: { type: DataTypes.DECIMAL(12, 2), allowNull: false },
    currency: { type: DataTypes.STRING, allowNull: false, defaultValue: 'INR' },
    status: { type: DataTypes.STRING, allowNull: false, defaultValue: 'PENDING' },
    rawResponse: { type: DataTypes.JSON, allowNull: true },
    paidAt: { type: DataTypes.DATE, allowNull: true },
    refundAmount: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
    refundId: { type: DataTypes.STRING, allowNull: true },
    refundStatus: { type: DataTypes.STRING, allowNull: true },
    createdAt: { type: DataTypes.DATE, allowNull: false },
    updatedAt: { type: DataTypes.DATE, allowNull: false }
  });

  // 5. flight_bookings
  await queryInterface.createTable('flight_bookings', {
    id: { type: DataTypes.STRING, primaryKey: true },
    bookingId: { type: DataTypes.STRING, allowNull: false, unique: true },
    pnr: { type: DataTypes.STRING, allowNull: false },
    ticketNumber: { type: DataTypes.STRING, allowNull: false },
    invoiceNumber: { type: DataTypes.STRING, allowNull: true },
    userId: { type: DataTypes.STRING, allowNull: true },
    packageId: { type: DataTypes.INTEGER, allowNull: true },
    itineraryDayId: { type: DataTypes.STRING, allowNull: true },
    serviceItemId: { type: DataTypes.STRING, allowNull: true },
    status: { type: DataTypes.STRING, allowNull: false, defaultValue: 'CONFIRMED' },
    airline: { type: DataTypes.STRING, allowNull: false },
    airlineCode: { type: DataTypes.STRING, allowNull: false },
    flightNumber: { type: DataTypes.STRING, allowNull: false },
    origin: { type: DataTypes.STRING, allowNull: false },
    originCity: { type: DataTypes.STRING, allowNull: true },
    destination: { type: DataTypes.STRING, allowNull: false },
    destinationCity: { type: DataTypes.STRING, allowNull: true },
    departureTime: { type: DataTypes.STRING, allowNull: false },
    arrivalTime: { type: DataTypes.STRING, allowNull: false },
    departureDate: { type: DataTypes.STRING, allowNull: false },
    arrivalDate: { type: DataTypes.STRING, allowNull: true },
    duration: { type: DataTypes.STRING, allowNull: true },
    stops: { type: DataTypes.STRING, defaultValue: 'Direct' },
    cabinClass: { type: DataTypes.STRING, defaultValue: 'Economy' },
    isLcc: { type: DataTypes.BOOLEAN, defaultValue: false },
    isRefundable: { type: DataTypes.BOOLEAN, defaultValue: true },
    fare: { type: DataTypes.DECIMAL(10, 2), allowNull: false },
    baseFare: { type: DataTypes.DECIMAL(10, 2), allowNull: false },
    tax: { type: DataTypes.DECIMAL(10, 2), allowNull: false },
    totalAmount: { type: DataTypes.DECIMAL(10, 2), allowNull: false },
    currency: { type: DataTypes.STRING, defaultValue: 'INR' },
    segments: { type: DataTypes.JSON, defaultValue: [] },
    passengers: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
    seats: { type: DataTypes.JSON, defaultValue: [] },
    ssr: { type: DataTypes.JSON, defaultValue: {} },
    fareRules: { type: DataTypes.JSON, allowNull: true },
    traceId: { type: DataTypes.STRING, allowNull: true },
    srdvIndex: { type: DataTypes.STRING, allowNull: true },
    resultIndex: { type: DataTypes.STRING, allowNull: true },
    cancellationDetails: { type: DataTypes.JSON, allowNull: true },
    refundDetails: { type: DataTypes.JSON, allowNull: true },
    ticketPdfUrl: { type: DataTypes.STRING, allowNull: true },
    bookingSnapshot: { type: DataTypes.JSON, allowNull: false, defaultValue: {} },
    createdAt: { type: DataTypes.DATE, allowNull: false },
    updatedAt: { type: DataTypes.DATE, allowNull: false }
  });

  // 6. hotel_bookings
  await queryInterface.createTable('hotel_bookings', {
    id: { type: DataTypes.STRING, primaryKey: true },
    bookingId: { type: DataTypes.STRING, allowNull: false, unique: true },
    confirmationNo: { type: DataTypes.STRING, allowNull: false },
    bookingRefNo: { type: DataTypes.STRING, allowNull: false },
    invoiceNumber: { type: DataTypes.STRING, allowNull: true },
    userId: { type: DataTypes.STRING, allowNull: true },
    packageId: { type: DataTypes.INTEGER, allowNull: true },
    itineraryDayId: { type: DataTypes.STRING, allowNull: true },
    serviceItemId: { type: DataTypes.STRING, allowNull: true },
    status: { type: DataTypes.STRING, allowNull: false, defaultValue: 'CONFIRMED' },
    hotelName: { type: DataTypes.STRING, allowNull: false },
    hotelCode: { type: DataTypes.STRING, allowNull: true },
    starRating: { type: DataTypes.INTEGER, defaultValue: 4 },
    category: { type: DataTypes.STRING, defaultValue: '4 Star' },
    address: { type: DataTypes.STRING, allowNull: true },
    city: { type: DataTypes.STRING, allowNull: false },
    state: { type: DataTypes.STRING, allowNull: true },
    country: { type: DataTypes.STRING, defaultValue: 'India' },
    checkInDate: { type: DataTypes.STRING, allowNull: false },
    checkOutDate: { type: DataTypes.STRING, allowNull: false },
    nights: { type: DataTypes.INTEGER, defaultValue: 1 },
    roomsCount: { type: DataTypes.INTEGER, defaultValue: 1 },
    guestCount: { type: DataTypes.INTEGER, defaultValue: 2 },
    roomTypeName: { type: DataTypes.STRING, allowNull: false, defaultValue: 'Deluxe Room' },
    ratePlanCode: { type: DataTypes.STRING, allowNull: true },
    inclusions: { type: DataTypes.JSON, defaultValue: ['Breakfast Included', 'Free Wi-Fi'] },
    cancellationPolicy: { type: DataTypes.JSON, allowNull: true },
    guests: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
    rooms: { type: DataTypes.JSON, defaultValue: [] },
    pricePerNight: { type: DataTypes.DECIMAL(10, 2), allowNull: false },
    basePrice: { type: DataTypes.DECIMAL(10, 2), allowNull: false },
    tax: { type: DataTypes.DECIMAL(10, 2), allowNull: false },
    totalAmount: { type: DataTypes.DECIMAL(10, 2), allowNull: false },
    currency: { type: DataTypes.STRING, defaultValue: 'INR' },
    voucherStatus: { type: DataTypes.STRING, defaultValue: 'CONFIRMED' },
    voucherPdfUrl: { type: DataTypes.STRING, allowNull: true },
    traceId: { type: DataTypes.STRING, allowNull: true },
    srdvIndex: { type: DataTypes.STRING, allowNull: true },
    resultIndex: { type: DataTypes.STRING, allowNull: true },
    cancellationDetails: { type: DataTypes.JSON, allowNull: true },
    refundDetails: { type: DataTypes.JSON, allowNull: true },
    bookingSnapshot: { type: DataTypes.JSON, allowNull: false, defaultValue: {} },
    createdAt: { type: DataTypes.DATE, allowNull: false },
    updatedAt: { type: DataTypes.DATE, allowNull: false }
  });

  // 7. bus_bookings
  await queryInterface.createTable('bus_bookings', {
    id: { type: DataTypes.STRING, primaryKey: true },
    bookingId: { type: DataTypes.STRING, allowNull: false, unique: true },
    ticketNo: { type: DataTypes.STRING, allowNull: false },
    operatorPnr: { type: DataTypes.STRING, allowNull: false },
    busId: { type: DataTypes.STRING, allowNull: true },
    userId: { type: DataTypes.STRING, allowNull: true },
    packageId: { type: DataTypes.INTEGER, allowNull: true },
    itineraryDayId: { type: DataTypes.STRING, allowNull: true },
    serviceItemId: { type: DataTypes.STRING, allowNull: true },
    status: { type: DataTypes.STRING, allowNull: false, defaultValue: 'CONFIRMED' },
    operator: { type: DataTypes.STRING, allowNull: false },
    busType: { type: DataTypes.STRING, allowNull: false },
    route: { type: DataTypes.STRING, allowNull: true },
    fromCity: { type: DataTypes.STRING, allowNull: false },
    toCity: { type: DataTypes.STRING, allowNull: false },
    travelDate: { type: DataTypes.STRING, allowNull: false },
    departureTime: { type: DataTypes.STRING, allowNull: false },
    arrivalTime: { type: DataTypes.STRING, allowNull: false },
    duration: { type: DataTypes.STRING, allowNull: true },
    boardingPoint: { type: DataTypes.JSON, allowNull: false, defaultValue: {} },
    droppingPoint: { type: DataTypes.JSON, allowNull: false, defaultValue: {} },
    passengers: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
    seats: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
    fare: { type: DataTypes.DECIMAL(10, 2), allowNull: false },
    tax: { type: DataTypes.DECIMAL(10, 2), defaultValue: 0 },
    totalAmount: { type: DataTypes.DECIMAL(10, 2), allowNull: false },
    currency: { type: DataTypes.STRING, defaultValue: 'INR' },
    ticketPdfUrl: { type: DataTypes.STRING, allowNull: true },
    traceId: { type: DataTypes.STRING, allowNull: true },
    resultIndex: { type: DataTypes.STRING, allowNull: true },
    cancellationDetails: { type: DataTypes.JSON, allowNull: true },
    refundDetails: { type: DataTypes.JSON, allowNull: true },
    bookingSnapshot: { type: DataTypes.JSON, allowNull: false, defaultValue: {} },
    createdAt: { type: DataTypes.DATE, allowNull: false },
    updatedAt: { type: DataTypes.DATE, allowNull: false }
  });

  // 8. car_bookings
  await queryInterface.createTable('car_bookings', {
    id: { type: DataTypes.STRING, primaryKey: true },
    bookingId: { type: DataTypes.STRING, allowNull: false, unique: true },
    confirmationNo: { type: DataTypes.STRING, allowNull: false },
    referenceNo: { type: DataTypes.STRING, allowNull: false },
    userId: { type: DataTypes.STRING, allowNull: true },
    packageId: { type: DataTypes.INTEGER, allowNull: true },
    itineraryDayId: { type: DataTypes.STRING, allowNull: true },
    serviceItemId: { type: DataTypes.STRING, allowNull: true },
    status: { type: DataTypes.STRING, allowNull: false, defaultValue: 'CONFIRMED' },
    vehicleName: { type: DataTypes.STRING, allowNull: false },
    category: { type: DataTypes.STRING, allowNull: false },
    type: { type: DataTypes.STRING, defaultValue: 'Sedan' },
    seatingCapacity: { type: DataTypes.INTEGER, defaultValue: 4 },
    pickupCity: { type: DataTypes.STRING, allowNull: false },
    dropCity: { type: DataTypes.STRING, allowNull: false },
    pickupLocation: { type: DataTypes.STRING, allowNull: true },
    dropLocation: { type: DataTypes.STRING, allowNull: true },
    pickupDate: { type: DataTypes.STRING, allowNull: false },
    pickupTime: { type: DataTypes.STRING, defaultValue: '09:00 AM' },
    tripType: { type: DataTypes.STRING, defaultValue: 'OneWay' },
    passengers: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
    driverDetails: { type: DataTypes.JSON, allowNull: true },
    perKmRate: { type: DataTypes.DECIMAL(10, 2), defaultValue: 14 },
    baseFare: { type: DataTypes.DECIMAL(10, 2), allowNull: false },
    driverAllowance: { type: DataTypes.DECIMAL(10, 2), defaultValue: 350 },
    tollIncluded: { type: DataTypes.BOOLEAN, defaultValue: true },
    totalAmount: { type: DataTypes.DECIMAL(10, 2), allowNull: false },
    currency: { type: DataTypes.STRING, defaultValue: 'INR' },
    voucherPdfUrl: { type: DataTypes.STRING, allowNull: true },
    traceId: { type: DataTypes.STRING, allowNull: true },
    srdvIndex: { type: DataTypes.STRING, allowNull: true },
    resultIndex: { type: DataTypes.STRING, allowNull: true },
    cancellationDetails: { type: DataTypes.JSON, allowNull: true },
    refundDetails: { type: DataTypes.JSON, allowNull: true },
    bookingSnapshot: { type: DataTypes.JSON, allowNull: false, defaultValue: {} },
    createdAt: { type: DataTypes.DATE, allowNull: false },
    updatedAt: { type: DataTypes.DATE, allowNull: false }
  });
}

export async function down(queryInterface) {
  await queryInterface.dropTable('car_bookings');
  await queryInterface.dropTable('bus_bookings');
  await queryInterface.dropTable('hotel_bookings');
  await queryInterface.dropTable('flight_bookings');
  await queryInterface.dropTable('payments');
  await queryInterface.dropTable('service_api_logs');
  await queryInterface.dropTable('package_service_items');
  await queryInterface.dropTable('travel_search_sessions');
}
